config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :expedients, only: [:create] do
    get :check, on: :collection
    get :verify, on: :collection
    get :thanks, on: :member
  end

  resources :pages, only: [] do
    get :find, on: :collection
    get :thanks, on: :collection
  end

  get 'fati', to: 'home#new_whatsapp', as: :new_whatsapp
  post 'register_whatsapp', to: 'home#register_whatsapp', as: :register_whatsapp

  namespace :panel do
    root to: 'home#index'

    resources :profile, only: [:edit, :update]
    resources :versions, only: [:show]

    resources :admin_settings, only: [] do
      put :table_columns, on: :collection
    end

    resources :institution_calendars, only: [:index, :show, :new] do
      resources :calendar_events, only: [:new, :edit]
    end

    resources :expedients do
      put :updates, on: :collection
      put :destroys, on: :collection
      get :list, on: :collection
      get :documents, on: :member
      post :redirect, on: :member
      post :tags, on: :member
      resources :events, only: [:create, :update]
      resources :managements, only: [:create]
    end

    resources :managements, only: [:update] do
      post :close, on: :member
      resources :comments, only: [:create]
    end

    resources :statistics, only: [:index] do
      get :managementsassigned, on: :member
      get :administrativearea, on: :member
      get :scategories,        on: :member
      get :entryways,          on: :member
      get :branches,           on: :member
      get :details,            on: :collection
      get :cities,             on: :member
      get :tags,               on: :member
    end

    [
      :institutions,
      :oir_addresses,
      :calendar_events,
      :information_requests,
      :users,
      :occupations,
      :documents,
      :entry_ways,
      :management_categories,
      :branches
    ].each do |resource|
      resources resource do
        put :updates, on: :collection
        put :destroys, on: :collection
        get :list, on: :collection
      end
    end

    resources :institutions, only: [] do
      member do
        post 'settings'
        get 'unlock'
      end
    end
    resources :branches, only: [] do
      member do
        post 'settings'
        get 'unlock'
      end
    end
  end
end

app/controllers/concerns/panel/crud.rb
# frozen_string_literal: true
module Panel
  #
  module Crud
    extend ActiveSupport::Concern

    included do
      respond_to :html
      before_action :set_item, only: [:show, :edit, :update, :destroy]
      before_action :set_uniq_institution!, only: [:update]

      helper_method :model
    end

    def index
      respond_to do |format|
        format.json { super }
        format.csv  { super }
        format.html { respond_to_html }
      end
    end

    def respond_to_html
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(:many), index_url
      render template: 'concerns/panel/index'
    end

    def new
      @item = model.new

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def create
      @item = model.new item_params
      set_uniq_institution!
      return redirect_to(edit_url, flash: { saved: true }) if @item.save

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def edit
      init_form
      breadcrumbs_for(:edit)

      render template: 'concerns/panel/form'
    end

    def update
      respond_to do |format|
        format.json { super }
        format.html do
          return redirect_to(edit_url, flash: { saved: true }) if
            @item.update_attributes(item_params)

          breadcrumbs_for(:edit)
          init_form
          render template: 'concerns/panel/form'
        end
      end
    end

    def destroy
      if @item.destroy
        redirect_to index_url, flash: { destroyed: true }
      else
        redirect_to index_url, flash: { destroyed: false, errors: @item.errors.full_messages }
      end
    end

    def init_form
    end

    def set_uniq_institution!
      return unless @item.respond_to? :institution_id
      #return unless current_user.one_institution?
      @item.institution_id = current_user.uniq_institution.try(:id)
    end

    private

    def item_params
      perms = params.require(:item).permit(permits)
      #perms.delete(:institution_id) if current_user.one_institution?
      perms
    end

    def set_item
      @item = if model.respond_to?(:friendly)
                model.friendly.find params[:id]
              else
                model.find params[:id]
              end
    end

    def show_url
      url_for(action: :show, id: @item)
    end

    def edit_url
      url_for(action: :edit, id: @item)
    end

    def index_url
      url_for(controller: model.to_s.underscore.pluralize, action: :index)
    end

    def humanized_model_name(count = 1)
      t(model.to_s.underscore, scope: 'activerecord.models', count: count)
    end

    def breadcrumbs_for(action)
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(count: :many), index_url
      add_breadcrumb t(action.to_s), nil
    end
  end
end

app/controllers/concerns/panel/multiple.rb
# frozen_string_literal: true
module Panel
  #
  module Multiple
    extend ActiveSupport::Concern

    included do
      respond_to :json

      before_action :ngtable_to_rails_filter_param, only: [:index]
      before_action :ngtable_to_rails_sort_param,   only: [:index]
    end

    def update
      respond_to do |format|
        format.html { super }
        format.json do
          sleep 0.5

          return render json: { success: true } if
            @item.update_attributes(item_params)

          render json: { success: false }
        end
      end
    end

    def updates
      model.where(id: params[:ids]).each do |item|
        item.assign_attributes(item_params.to_hash)
        item.save(validate: false)
      end
    end

    def destroys
      model.where(id: params[:ids]).each(&:destroy)
    end

    def index
      respond_to do |format|
        format.html { super }
        format.csv  { super }
        format.json { respond_to_json }
      end
    end

    def respond_to_json
      @q = model.ransack(params[:filter])
      @c = @q.result.paginate(page: params[:page], per_page: params[:count])

      render json: json_result(@c)
    end

    def json_result(collection)
      {
        result:        json_parsed(collection),
        total_entries: collection.total_entries,
        admin_setting: current_user.admin_setting
      }
    end

    def json_parsed(c)
      c.decorate.as_json(include: json_includes, methods: json_methods)
    end

    def json_includes
      nil
    end

    def json_methods
      nil
    end

    def list
      render json: model
        .select(:id, model.acts_as_label)
        .order(model.acts_as_label)
        .to_json
    end

    private

    def ngtable_to_rails_filter_param
      return unless params.key?(:filter)
      params[:filter]
        .update(params[:filter]) { |_k, v| URI.decode(v) }
        .delete_if { |_k, v| v == 'null' }
    end

    def ngtable_to_rails_sort_param
      return unless params.key?(:sorting)

      params[:filter] ||= {}
      params[:filter][:s] = params[:sorting].flatten.join(' ')
    end
  end
end

app/controllers/panel/admin_settings_controller.rb
# frozen_string_literal: true
module Panel
  #
  class AdminSettingsController < PanelController
    before_action :fetch_admin_setting

    def table_columns
      @admin_setting.update_table_columns(item_params[:table_columns])
    end

    # private

    def item_params
      params.require(:admin_setting).tap do |whitelisted|
        whitelisted[:table_columns] = params[:admin_setting][:table_columns]
      end
    end

    def fetch_admin_setting
      @admin_setting = AdminSetting
                       .where(user_id: current_user.id)
                       .first_or_create
    end
  end
end

app/controllers/panel/branches_controller.rb
# frozen_string_literal: true
module Panel
  #
  class BranchesController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      Branch
    end

    def permits
      [:name, :address, :institution_id]
    end

    def respond_to_json
      @q = model.accessible_by(current_ability)
      @q = @q.ransack(params[:filter])
      @c = @q.result.paginate(page: params[:page], per_page: params[:count])

      render json: json_result(@c)
    end

    def edit
      init_form
      breadcrumbs_for(:edit)

      render template: 'panel/branches/form'
    end

    def new
      @item = model.new

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/branches/form'
    end

    def create
      @item = model.new item_params
      set_uniq_institution! if current_user.one_institution?
      if @item.save
        return redirect_to(edit_url, flash: { saved: true })
      end
      init_form
      breadcrumbs_for(:new)
      render template: 'panel/branches/form'
    end

    def update
      @item.attributes = item_params
      if @item.save
        return redirect_to(edit_url, flash: { saved: true })
      end
      init_form
      breadcrumbs_for(:edit)
      render template: 'panel/branches/form'
    end

    def init_form
      if current_user.has_role?("admin")
        @institutions = Institution.order(Institution.acts_as_label)
      else
        @institutions = Institution.where("id IN (?)", current_user.institution_ids)
      end
    end

    def settings
      branch = Branch.find params[:id]
      redirect_to panel_branches_url and return unless branch

      branch.settings.mon = params[:mon]
      branch.settings.tue = params[:tue]
      branch.settings.wed = params[:wed]
      branch.settings.thu = params[:thu]
      branch.settings.fri = params[:fri]
      branch.settings.sat = params[:sat]
      branch.settings.holidays = params[:days]
      branch.settings.response_days = params[:response_days]
      redirect_to edit_panel_branch_url, flash: {saved: true}
    end

    def unlock
      branch = Branch.find params[:id]
      redirect_to panel_branches_url and return if branch.can_edit?
      branch.update_column(:can_edit, true)
      branch.schedule_can_edit_closure
      redirect_to panel_branches_url and return
    end

    private
    def json_methods
      [ :institution_name ]
    end

  end
end

app/controllers/panel/calendar_events_controller.rb
# frozen_string_literal: true
module Panel
  #
  class CalendarEventsController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      CalendarEvent
    end

    def create
      @item = model.new item_params
      @item.user_id = current_user.id
      @item.institution_calendar_id = params[:institution_calendar_id]
      return redirect_to(edit_url, flash: { saved: true }) if @item.save

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def permits
      [:name, :description, :kind, :start_at, :end_at, :repetitive]
    end

    def exportable_fields
      [:name]
    end

    def respond_to_html
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(:many), index_url
      render template: 'panel/calendar_events/index'
    end

    def breadcrumbs_for(action)
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb "Listado de eventos", panel_institution_calendar_url(params[:institution_calendar_id])
      add_breadcrumb t(action.to_s), nil
    end

  end
end

app/controllers/panel/comments_controller.rb
# frozen_string_literal: true
module Panel
  #
  class CommentsController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      Comment
    end

    def permits
      [:comment]
    end

    def exportable_fields
      []
    end

    def create
      management = Management.find params[:management_id]
      item = management.expedient
      comment = management.comments.new item_params
      comment.user_id = current_user.id
      success = comment.save
      respond_to do |format|
        # Save assets
        if params[:file]
          params[:file].each do |k, file|
            Asset.create attachment: file, assetable: comment
          end
        end
        format.html {
          return redirect_to panel_expedient_url(item, anchor: "management-#{management.id}")
        }
        format.json {
          render json: {code: 200, item: comment, redirect_url: panel_expedient_url(item, anchor: "management-#{management.id}")}
        }
      end
    end

    def item_params
      perms = params.require(:comment).permit(permits)
      perms
    end


  end
end

app/controllers/panel/entry_ways_controller.rb
# frozen_string_literal: true
module Panel
  #
  class EntryWaysController < PanelController
    before_action :check_admin
    include Panel::Crud
    include Panel::Multiple


    def model
      EntryWay
    end

    def permits
      [
        :classification, :institution_id, :name
      ]
    end

    def init_form
      if current_user.has_role?("admin")
        @institutions = Institution.order(Institution.acts_as_label)
      else
        @institutions = Institution.where("id IN (?)", current_user.institution_ids)
      end
    end

    def respond_to_json
      @q = model.accessible_by(current_ability)
      @q = @q.ransack(params[:filter])
      @c = @q.result.paginate(page: params[:page], per_page: params[:count])

      render json: json_result(@c)
    end

    def create
      @item = model.new item_params
      set_uniq_institution! if current_user.one_institution?
      if @item.save
        return redirect_to(edit_url, flash: { saved: true })
      end
      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def update
      @item.attributes = item_params
      if @item.save
        return redirect_to(edit_url, flash: { saved: true })
      end
      init_form
      breadcrumbs_for(:edit)
      render template: 'concerns/panel/form'
    end

    private

    def check_admin
      if current_user.has_role?("administrative_unit")
        redirect_to panel_root_url
      end
    end

    def json_methods
      [ :institution_name, :classification_s ]
    end

  end
end

app/controllers/panel/events_controller.rb
# frozen_string_literal: true
module Panel
  #
  class EventsController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      Event
    end

    def permits
      [:start_at, :justification, :state, :failed_attempt, :classification_type, :resolution_type, :it_proceeds, :response]
    end

    def exportable_fields
      []
    end

    def create
      @item = Expedient.find params[:expedient_id]
      @event = @item.events.new(item_params)
      @event.response = @event.response == 1 ? true : false if @event.response.present?
      if @event.failed_attempt.to_i == 1
        @event.state = 'failed_communication_attempt'
      else
        case @item.state
        when 'new'
          @event.state = 'process'
          @event.state = 'closed' if @event.classification_type.present?
        when 'process'
          @event.state = 'closed'
        end
      end
      @event.user_id = current_user.id

      success = @event.save
      respond_to do |format|
        format.html {
          if success
            if (@event.state == 'process') and (@item.events.where(state: 'process').any? and @item.anonymous == false) and @item.quick_case.to_i == 0
              start_at = @item.received_at
              contact_at = @event.start_at
              @item.update_column(:contact_business_days, start_at.to_date.business_days_until(contact_at.to_date))
              @item.update_column(:contact_business_hours, start_at.business_time_until(contact_at).to_f/60/60)
            elsif @event.state == 'closed'
              @item.save!
            end
            return redirect_to(panel_expedient_url(@item), flash: {saved: true})
          else
            @errors = @event.errors
            @management = @item.managements.new
            @tags = ActsAsTaggableOn::Tag.for_context(:tags)
            @managements    = @item.managements.reorder(created_at: :asc)
            render 'panel/expedients/show'
          end
        }
      end
    end

    def update
      @item = Expedient.find params[:expedient_id]
      @event = Event.find params[:id]
      @event.assign_attributes(item_params)
      @event.response = @event.response == 1 ? true : false if @event.response.present?
      if @event.valid?
        @event.update_column(:justification, params[:event][:justification])
        @item.update_columns(
          classification_type: params[:event][:classification_type],
          response: params[:event][:response],
          resolution_type: params[:event][:resolution_type],
          it_proceeds: params[:event][:it_proceeds]
        )
      end
      return redirect_to(panel_expedient_url(@item, anchor: 'close-expedient-area'), flash: {saved: true})
    end

    def item_params
      perms = params.require(:event).permit(permits)
      perms
    end


  end
end

app/helpers/management_helper.rb
module ManagementHelper
  def management_kind_for_filter
    Management::KIND.map{ |k, v| {id: k, title: v} }.to_json
  end
end

app/views/panel/managements/_management.haml
- if !management.new_record? && can?(:read, management) # Always have a new record
  .wrapper{ id: "management-#{management.id}" }
    .row.align-center
      .columns.large-24
        .container{ class: (management_counter + 1) == (management_iteration.size - 1) ? nil : 'm-b-0' }
          .row
            .columns.small-24.medium-4
              .management-date
                %strong
                  = l(management.created_at, format: :small)
                %small
                  = l(management.created_at, format: :hour)
            .columns.small-24.medium-20
              .management-info
                %p
                  - if management.assigned_names.present?
                    %strong
                      = management.user.try(:name)
                      asignó a
                    = management.assigned_names
                    %span.blue
                      una
                    %strong.orange
                      = management.full_classification
                  - else
                    %span.blue
                      = management.user.try(:name)
                      se asigno a si mismo un
                    %strong.orange
                      = management.full_classification
                %div
                  = sanitize management.comment
                - if management.assets.any?
                  %br
                  .row
                    .columns
                      = render management.assets
                = render management.comments
                %hr
                .text-right
                  - if management.process?
                    = link_to 'javascript:void(0)', 'data-open' => "commentModal#{management.id}", class: 'btn' do
                      %i.material-icons comment
                      Agregar comentario
                  - if can?(:manage, management) && management.process?
                    = link_to 'javascript:void(0)', 'data-open' => "closeModal#{management.id}", class: 'btn m-l-15' do
                      %i.material-icons close
                      Cerrar gestión
                  - if can?(:manage, management) and can?(:modify, management)
                    = link_to 'javascript:void(0)', 'data-open' => "editModal#{management.id}", class: 'btn m-l-15' do
                      %i.material-icons edit
                      Editar esta gestión
                / Modal comment
                .reveal{id: "commentModal#{management.id}", 'data-reveal' => true}
                  %h2 Agregar comentario
                  .form-popup
                    = form_for management.comments.new, url: panel_management_comments_url(management), html: { id: 'dropzone-expedients', class: 'dropzone', data: {preview: ".dropzone-previews-#{management.id}"} } do |f|
                      .control
                        .row.align-middle.align-justify
                          .columns.small-24
                            = f.text_field :comment, placeholder: 'Escribe un comentario...'
                      .control
                        .row.align-middle.align-justify
                          .columns.small-24
                            .dz-default.dz-message
                              %div{ class: "dropzone-previews-#{management.id}" }
                              %span
                                Arrastre o seleccione acá sus archivos
                      .control
                        .row.align-center.align-justify
                          .columns.small-5
                          .columns.small-18
                            = link_to 'javascript:void(0)', data: { close: '' }, class: 'm-r-15' do
                              %i.material-icons close
                              Cancelar
                            = f.button type: :submit, data: { disable_with: 'Por favor espere...' } do
                              %i.material-icons comment
                              Comentar
                - if can? :manage, management
                  / Modal close management
                  .reveal{id: "closeModal#{management.id}", 'data-reveal' => true}
                    %h2 Cierre de gestión
                    .form-popup
                      = form_for management.events.new, url: close_panel_management_url(management), html: { method: :post } do |f|
                        .control
                          .row.align-middle.align-justify
                            .columns.small-5= f.label :start_at, 'Fecha de cierre', class: 'required'
                            .columns.small-18
                              = f.datetime_select :start_at, {  }, class: 'date'
                              = f.hidden_field :weight, value: 1
                        -# .control
                        -#   .row.align-middle.align-justify
                        -#     .columns.small-5= f.label :weight, "Número de #{management.kind_s.upcase} procesadas", class: 'required'
                        -#     .columns.small-18= f.number_field :weight, value: 1, required: true
                        .control
                          .row.align-middle.align-justify
                            .columns.small-5= f.label :justification, 'Comentario final de cierre', class: 'required'
                            .columns.small-18
                              = f.text_area :justification, rows: 3, required: true
                        .control
                          .row.align-middle.align-justify
                            .columns.small-5= f.label :kind, 'Categoría', class: 'required'
                            .columns.small-18
                              = f.select :kind, options_for_select(Management::KIND.map{|k,v| [v, k, {'data-help' => t("help.#{k}")}]}, management.kind), {prompt: 'Seleccione'}, {required: true, data: {dependent: '', target: "category-management-#{management.id}", with_help: true}}
                              = display_error_for(:kind)
                              .help-text
                        .control
                          .row.align-middle.align-justify
                            .columns.small-5= f.label :management_category_id, 'Subcategoría', class: 'required'
                            .columns.small-18
                              = f.select :management_category_id, grouped_options_for_select(ManagementCategory::grouped_options(@item.institution_id), management.management_category_id), {prompt: 'Seleccione'}, {required: true, class: "category-management-#{management.id}"}
                              = display_error_for(:management_category_id)
                        .control
                          .row
                            .columns.small-24
                              %small * Campos requeridos
                        .control
                          .row.align-center.align-justify
                            .columns.small-5
                            .columns.small-18
                              = link_to '#', data: { close: '' }, class: 'm-r-15' do
                                %i.material-icons close
                                Cancelar
                              = f.button type: :submit, data: { disable_with: 'Guardando...' } do
                                %i.material-icons save
                                Guardar
                - if can?(:manage, management) and can?(:modify, management)
                  / Modal edit management
                  .reveal{id: "editModal#{management.id}", 'data-reveal' => true}
                    %h2 Editar gestión
                    .form-popup
                      = form_for management, url: panel_management_url(management), html: { method: :put } do |f|
                        .control
                          .row.align-middle.align-justify
                            .columns.small-5= f.label :deadline_at, 'Fecha tentativa de entrega', class: 'required'
                            .columns.small-18
                              = f.text_field :deadline_at, class: 'min-datepicker'
                              %small Para tramitar y recibir respuesta de la gestión, tiene #{@response_days} días hábiles, siempre puede cambiar esta fecha dejando constancia en los comentarios de las ampliaciones realizadas.
                        .control
                          .row.align-middle.align-justify
                            .columns.small-5= f.label :comment, "Gestión requerida", class: 'required'
                            .columns.small-18= f.text_area :comment, required: true, rows: 4
                        .control
                          .row.align-middle.align-justify
                            .columns.small-5= f.label :kind, 'Categoría', class: 'required'
                            .columns.small-18
                              = f.select :kind, options_for_select(Management::KIND.map{|k,v| [v, k, {'data-help' => t("help.#{k}")}]}, management.kind), {prompt: 'Seleccione'}, {required: true, data: {dependent: '', target: "edit-category-management-#{management.id}", with_help: true}}
                              .help-text
                              = display_error_for(:kind)
                        .control
                          .row.align-middle.align-justify
                            .columns.small-5= f.label :management_category_id, 'Subcategoría', class: 'required'
                            .columns.small-18
                              = f.select :management_category_id, grouped_options_for_select(ManagementCategory::grouped_options(@item.institution_id), management.management_category_id), {prompt: 'Seleccione'}, {required: true, class: "edit-category-management-#{management.id}"}
                              = display_error_for(:management_category_id)
                        .control
                          .row
                            .columns.small-24
                              %small * Campos requeridos
                        .control
                          .row.align-center.align-justify
                            .columns.small-5
                            .columns.small-18
                              = link_to '#', data: { close: '' }, class: 'm-r-15' do
                                %i.material-icons close
                                Cancelar
                              = f.button type: :submit, data: { disable_with: 'Guardando...' } do
                                %i.material-icons save
                                Guardar