config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :expedients, only: [:create] do
    get :check, on: :collection
    get :verify, on: :collection
    get :thanks, on: :member
  end

  resources :pages, only: [] do
    get :find, on: :collection
    get :thanks, on: :collection
  end

  get 'fati', to: 'home#new_whatsapp', as: :new_whatsapp
  post 'register_whatsapp', to: 'home#register_whatsapp', as: :register_whatsapp

  namespace :panel do
    root to: 'home#index'

    resources :profile, only: [:edit, :update]
    resources :versions, only: [:show]

    resources :admin_settings, only: [] do
      put :table_columns, on: :collection
    end

    resources :institution_calendars, only: [:index, :show, :new] do
      resources :calendar_events, only: [:new, :edit]
    end

    resources :expedients do
      put :updates, on: :collection
      put :destroys, on: :collection
      get :list, on: :collection
      get :documents, on: :member
      post :redirect, on: :member
      post :tags, on: :member
      resources :events, only: [:create, :update]
      resources :managements, only: [:create]
    end

    resources :managements, only: [:update] do
      post :close, on: :member
      resources :comments, only: [:create]
    end

    resources :statistics, only: [:index] do
      get :managementsassigned, on: :member
      get :administrativearea, on: :member
      get :scategories,        on: :member
      get :entryways,          on: :member
      get :branches,           on: :member
      get :details,            on: :collection
      get :cities,             on: :member
      get :tags,               on: :member
    end

    [
      :institutions,
      :oir_addresses,
      :calendar_events,
      :information_requests,
      :users,
      :occupations,
      :documents,
      :entry_ways,
      :management_categories,
      :branches
    ].each do |resource|
      resources resource do
        put :updates, on: :collection
        put :destroys, on: :collection
        get :list, on: :collection
      end
    end

    resources :institutions, only: [] do
      member do
        post 'settings'
        get 'unlock'
      end
    end
    resources :branches, only: [] do
      member do
        post 'settings'
        get 'unlock'
      end
    end
  end
end

app/models/institution_type.rb
class InstitutionType < ApplicationRecord
end

app/controllers/concerns/panel/crud.rb
# frozen_string_literal: true
module Panel
  #
  module Crud
    extend ActiveSupport::Concern

    included do
      respond_to :html
      before_action :set_item, only: [:show, :edit, :update, :destroy]
      before_action :set_uniq_institution!, only: [:update]

      helper_method :model
    end

    def index
      respond_to do |format|
        format.json { super }
        format.csv  { super }
        format.html { respond_to_html }
      end
    end

    def respond_to_html
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(:many), index_url
      render template: 'concerns/panel/index'
    end

    def new
      @item = model.new

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def create
      @item = model.new item_params
      set_uniq_institution!
      return redirect_to(edit_url, flash: { saved: true }) if @item.save

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def edit
      init_form
      breadcrumbs_for(:edit)

      render template: 'concerns/panel/form'
    end

    def update
      respond_to do |format|
        format.json { super }
        format.html do
          return redirect_to(edit_url, flash: { saved: true }) if
            @item.update_attributes(item_params)

          breadcrumbs_for(:edit)
          init_form
          render template: 'concerns/panel/form'
        end
      end
    end

    def destroy
      if @item.destroy
        redirect_to index_url, flash: { destroyed: true }
      else
        redirect_to index_url, flash: { destroyed: false, errors: @item.errors.full_messages }
      end
    end

    def init_form
    end

    def set_uniq_institution!
      return unless @item.respond_to? :institution_id
      #return unless current_user.one_institution?
      @item.institution_id = current_user.uniq_institution.try(:id)
    end

    private

    def item_params
      perms = params.require(:item).permit(permits)
      #perms.delete(:institution_id) if current_user.one_institution?
      perms
    end

    def set_item
      @item = if model.respond_to?(:friendly)
                model.friendly.find params[:id]
              else
                model.find params[:id]
              end
    end

    def show_url
      url_for(action: :show, id: @item)
    end

    def edit_url
      url_for(action: :edit, id: @item)
    end

    def index_url
      url_for(controller: model.to_s.underscore.pluralize, action: :index)
    end

    def humanized_model_name(count = 1)
      t(model.to_s.underscore, scope: 'activerecord.models', count: count)
    end

    def breadcrumbs_for(action)
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(count: :many), index_url
      add_breadcrumb t(action.to_s), nil
    end
  end
end

app/controllers/concerns/panel/multiple.rb
# frozen_string_literal: true
module Panel
  #
  module Multiple
    extend ActiveSupport::Concern

    included do
      respond_to :json

      before_action :ngtable_to_rails_filter_param, only: [:index]
      before_action :ngtable_to_rails_sort_param,   only: [:index]
    end

    def update
      respond_to do |format|
        format.html { super }
        format.json do
          sleep 0.5

          return render json: { success: true } if
            @item.update_attributes(item_params)

          render json: { success: false }
        end
      end
    end

    def updates
      model.where(id: params[:ids]).each do |item|
        item.assign_attributes(item_params.to_hash)
        item.save(validate: false)
      end
    end

    def destroys
      model.where(id: params[:ids]).each(&:destroy)
    end

    def index
      respond_to do |format|
        format.html { super }
        format.csv  { super }
        format.json { respond_to_json }
      end
    end

    def respond_to_json
      @q = model.ransack(params[:filter])
      @c = @q.result.paginate(page: params[:page], per_page: params[:count])

      render json: json_result(@c)
    end

    def json_result(collection)
      {
        result:        json_parsed(collection),
        total_entries: collection.total_entries,
        admin_setting: current_user.admin_setting
      }
    end

    def json_parsed(c)
      c.decorate.as_json(include: json_includes, methods: json_methods)
    end

    def json_includes
      nil
    end

    def json_methods
      nil
    end

    def list
      render json: model
        .select(:id, model.acts_as_label)
        .order(model.acts_as_label)
        .to_json
    end

    private

    def ngtable_to_rails_filter_param
      return unless params.key?(:filter)
      params[:filter]
        .update(params[:filter]) { |_k, v| URI.decode(v) }
        .delete_if { |_k, v| v == 'null' }
    end

    def ngtable_to_rails_sort_param
      return unless params.key?(:sorting)

      params[:filter] ||= {}
      params[:filter][:s] = params[:sorting].flatten.join(' ')
    end
  end
end

app/controllers/panel/admin_settings_controller.rb
# frozen_string_literal: true
module Panel
  #
  class AdminSettingsController < PanelController
    before_action :fetch_admin_setting

    def table_columns
      @admin_setting.update_table_columns(item_params[:table_columns])
    end

    # private

    def item_params
      params.require(:admin_setting).tap do |whitelisted|
        whitelisted[:table_columns] = params[:admin_setting][:table_columns]
      end
    end

    def fetch_admin_setting
      @admin_setting = AdminSetting
                       .where(user_id: current_user.id)
                       .first_or_create
    end
  end
end

app/controllers/panel/branches_controller.rb
# frozen_string_literal: true
module Panel
  #
  class BranchesController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      Branch
    end

    def permits
      [:name, :address, :institution_id]
    end

    def respond_to_json
      @q = model.accessible_by(current_ability)
      @q = @q.ransack(params[:filter])
      @c = @q.result.paginate(page: params[:page], per_page: params[:count])

      render json: json_result(@c)
    end

    def edit
      init_form
      breadcrumbs_for(:edit)

      render template: 'panel/branches/form'
    end

    def new
      @item = model.new

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/branches/form'
    end

    def create
      @item = model.new item_params
      set_uniq_institution! if current_user.one_institution?
      if @item.save
        return redirect_to(edit_url, flash: { saved: true })
      end
      init_form
      breadcrumbs_for(:new)
      render template: 'panel/branches/form'
    end

    def update
      @item.attributes = item_params
      if @item.save
        return redirect_to(edit_url, flash: { saved: true })
      end
      init_form
      breadcrumbs_for(:edit)
      render template: 'panel/branches/form'
    end

    def init_form
      if current_user.has_role?("admin")
        @institutions = Institution.order(Institution.acts_as_label)
      else
        @institutions = Institution.where("id IN (?)", current_user.institution_ids)
      end
    end

    def settings
      branch = Branch.find params[:id]
      redirect_to panel_branches_url and return unless branch

      branch.settings.mon = params[:mon]
      branch.settings.tue = params[:tue]
      branch.settings.wed = params[:wed]
      branch.settings.thu = params[:thu]
      branch.settings.fri = params[:fri]
      branch.settings.sat = params[:sat]
      branch.settings.holidays = params[:days]
      branch.settings.response_days = params[:response_days]
      redirect_to edit_panel_branch_url, flash: {saved: true}
    end

    def unlock
      branch = Branch.find params[:id]
      redirect_to panel_branches_url and return if branch.can_edit?
      branch.update_column(:can_edit, true)
      branch.schedule_can_edit_closure
      redirect_to panel_branches_url and return
    end

    private
    def json_methods
      [ :institution_name ]
    end

  end
end

app/controllers/panel/calendar_events_controller.rb
# frozen_string_literal: true
module Panel
  #
  class CalendarEventsController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      CalendarEvent
    end

    def create
      @item = model.new item_params
      @item.user_id = current_user.id
      @item.institution_calendar_id = params[:institution_calendar_id]
      return redirect_to(edit_url, flash: { saved: true }) if @item.save

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def permits
      [:name, :description, :kind, :start_at, :end_at, :repetitive]
    end

    def exportable_fields
      [:name]
    end

    def respond_to_html
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(:many), index_url
      render template: 'panel/calendar_events/index'
    end

    def breadcrumbs_for(action)
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb "Listado de eventos", panel_institution_calendar_url(params[:institution_calendar_id])
      add_breadcrumb t(action.to_s), nil
    end

  end
end

app/controllers/panel/comments_controller.rb
# frozen_string_literal: true
module Panel
  #
  class CommentsController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      Comment
    end

    def permits
      [:comment]
    end

    def exportable_fields
      []
    end

    def create
      management = Management.find params[:management_id]
      item = management.expedient
      comment = management.comments.new item_params
      comment.user_id = current_user.id
      success = comment.save
      respond_to do |format|
        # Save assets
        if params[:file]
          params[:file].each do |k, file|
            Asset.create attachment: file, assetable: comment
          end
        end
        format.html {
          return redirect_to panel_expedient_url(item, anchor: "management-#{management.id}")
        }
        format.json {
          render json: {code: 200, item: comment, redirect_url: panel_expedient_url(item, anchor: "management-#{management.id}")}
        }
      end
    end

    def item_params
      perms = params.require(:comment).permit(permits)
      perms
    end


  end
end

app/controllers/panel/entry_ways_controller.rb
# frozen_string_literal: true
module Panel
  #
  class EntryWaysController < PanelController
    before_action :check_admin
    include Panel::Crud
    include Panel::Multiple


    def model
      EntryWay
    end

    def permits
      [
        :classification, :institution_id, :name
      ]
    end

    def init_form
      if current_user.has_role?("admin")
        @institutions = Institution.order(Institution.acts_as_label)
      else
        @institutions = Institution.where("id IN (?)", current_user.institution_ids)
      end
    end

    def respond_to_json
      @q = model.accessible_by(current_ability)
      @q = @q.ransack(params[:filter])
      @c = @q.result.paginate(page: params[:page], per_page: params[:count])

      render json: json_result(@c)
    end

    def create
      @item = model.new item_params
      set_uniq_institution! if current_user.one_institution?
      if @item.save
        return redirect_to(edit_url, flash: { saved: true })
      end
      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def update
      @item.attributes = item_params
      if @item.save
        return redirect_to(edit_url, flash: { saved: true })
      end
      init_form
      breadcrumbs_for(:edit)
      render template: 'concerns/panel/form'
    end

    private

    def check_admin
      if current_user.has_role?("administrative_unit")
        redirect_to panel_root_url
      end
    end

    def json_methods
      [ :institution_name, :classification_s ]
    end

  end
end

app/controllers/panel/events_controller.rb
# frozen_string_literal: true
module Panel
  #
  class EventsController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      Event
    end

    def permits
      [:start_at, :justification, :state, :failed_attempt, :classification_type, :resolution_type, :it_proceeds, :response]
    end

    def exportable_fields
      []
    end

    def create
      @item = Expedient.find params[:expedient_id]
      @event = @item.events.new(item_params)
      @event.response = @event.response == 1 ? true : false if @event.response.present?
      if @event.failed_attempt.to_i == 1
        @event.state = 'failed_communication_attempt'
      else
        case @item.state
        when 'new'
          @event.state = 'process'
          @event.state = 'closed' if @event.classification_type.present?
        when 'process'
          @event.state = 'closed'
        end
      end
      @event.user_id = current_user.id

      success = @event.save
      respond_to do |format|
        format.html {
          if success
            if (@event.state == 'process') and (@item.events.where(state: 'process').any? and @item.anonymous == false) and @item.quick_case.to_i == 0
              start_at = @item.received_at
              contact_at = @event.start_at
              @item.update_column(:contact_business_days, start_at.to_date.business_days_until(contact_at.to_date))
              @item.update_column(:contact_business_hours, start_at.business_time_until(contact_at).to_f/60/60)
            elsif @event.state == 'closed'
              @item.save!
            end
            return redirect_to(panel_expedient_url(@item), flash: {saved: true})
          else
            @errors = @event.errors
            @management = @item.managements.new
            @tags = ActsAsTaggableOn::Tag.for_context(:tags)
            @managements    = @item.managements.reorder(created_at: :asc)
            render 'panel/expedients/show'
          end
        }
      end
    end

    def update
      @item = Expedient.find params[:expedient_id]
      @event = Event.find params[:id]
      @event.assign_attributes(item_params)
      @event.response = @event.response == 1 ? true : false if @event.response.present?
      if @event.valid?
        @event.update_column(:justification, params[:event][:justification])
        @item.update_columns(
          classification_type: params[:event][:classification_type],
          response: params[:event][:response],
          resolution_type: params[:event][:resolution_type],
          it_proceeds: params[:event][:it_proceeds]
        )
      end
      return redirect_to(panel_expedient_url(@item, anchor: 'close-expedient-area'), flash: {saved: true})
    end

    def item_params
      perms = params.require(:event).permit(permits)
      perms
    end


  end
end

app/controllers/panel/occupations_controller.rb
# frozen_string_literal: true
module Panel
  #
  class OccupationsController < PanelController
    include Panel::Crud
    include Panel::Multiple
    
    def model
      Occupation
    end

    def permits
      [:name]
    end

    def exportable_fields
      [:name]
    end

  end
end

app/views/panel/institutions/_actions.haml
.row.align-middle
  .columns.small-6
    .actions
      .row.align-stretch
        .columns.shrink
          -# %input.decorated-checkbox.box{ type: :checkbox, class: 'all', ng: { model: 'checkboxes.checked' }}

        .columns
          -# %div{ ng: { show: 'checkboxes.checked || indeterminate' }}
          -#   = link_to nil, class: 'btn', 'ng-click' => 'deleteSelection($event)' do
          -#     %i.material-icons delete

          %strong.total-entries{ 'ng-bind' => "total_entries + ' Registros'" }

  .columns.small-18
    .visibility-controls
      = label_tag nil, 'ng-repeat' => 'col in table.cols' do
        %input{ type: :checkbox, ng: { model_options: "{ getterSetter: true }", model: 'col.show' }}
        %span {{ col.title() }}

app/views/panel/institutions/_form.haml
.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :avatar

    - if f.object.persisted? && f.object.avatar.present?
      .columns.small-15= f.file_field :avatar
      .columns.small-2
        = link_to f.object.avatar.url, target: '_blank' do
          %i.material-icons file_download
    - else
      .columns.small-18= f.file_field :avatar

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :acronym
    .columns.small-18= f.text_field :acronym

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :name
    .columns.small-18= f.text_field :name

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :correlative
    .columns.small-18= f.number_field :correlative

%h3
  Información de contacto, disponible para los ciudadanos

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :address
    .columns.small-18= f.text_area :address

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :responsible_unit
    .columns.small-18= f.text_field :responsible_unit

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :email
    .columns.small-18= f.email_field :email

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :phone
    .columns.small-18= f.text_field :phone

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :whatsapp
    .columns.small-18= f.text_field :whatsapp

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :facebook
    .columns.small-18= f.text_field :facebook

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :twitter
    .columns.small-18= f.text_field :twitter

app/views/panel/institutions/_settings.haml
- if @item.new_record?
  %p
    Por favor cree la institución para poder configurar sus horarios y asuetos
- else
  = form_for :setting, url: settings_panel_institution_url(@item) do |f|
    .control
      .row.align-middle
        .columns
          %strong
            Horarios de trabajo
    .control
      .row.align-middle
        .columns.small-6.medium-5.large-4= f.label :mon, 'Lunes'
        .columns.small-9.medium-5.large-4= select_tag 'mon[]', options_for_select(Institution.times, @item.settings.mon[0]), {include_blank: 'Entrada', class: 'input-times'}
        .columns.small-9.medium-5.large-4= select_tag 'mon[]', options_for_select(Institution.times, @item.settings.mon[1]), {include_blank: 'Salida', class: 'input-times'}
    .control
      .row.align-middle
        .columns.small-6.medium-5.large-4= f.label :mon, 'Martes'
        .columns.small-9.medium-5.large-4= select_tag 'tue[]', options_for_select(Institution.times, @item.settings.tue[0]), {include_blank: 'Entrada', class: 'input-times'}
        .columns.small-9.medium-5.large-4= select_tag 'tue[]', options_for_select(Institution.times, @item.settings.tue[1]), {include_blank: 'Salida', class: 'input-times'}
    .control
      .row.align-middle
        .columns.small-6.medium-5.large-4= f.label :mon, 'Miércoles'
        .columns.small-9.medium-5.large-4= select_tag 'wed[]', options_for_select(Institution.times, @item.settings.wed[0]), {include_blank: 'Entrada', class: 'input-times'}
        .columns.small-9.medium-5.large-4= select_tag 'wed[]', options_for_select(Institution.times, @item.settings.wed[1]), {include_blank: 'Salida', class: 'input-times'}
    .control
      .row.align-middle
        .columns.small-6.medium-5.large-4= f.label :mon, 'Jueves'
        .columns.small-9.medium-5.large-4= select_tag 'thu[]', options_for_select(Institution.times, @item.settings.thu[0]), {include_blank: 'Entrada', class: 'input-times'}
        .columns.small-9.medium-5.large-4= select_tag 'thu[]', options_for_select(Institution.times, @item.settings.thu[1]), {include_blank: 'Salida', class: 'input-times'}
    .control
      .row.align-middle
        .columns.small-6.medium-5.large-4= f.label :mon, 'Viernes'
        .columns.small-9.medium-5.large-4= select_tag 'fri[]', options_for_select(Institution.times, @item.settings.fri[0]), {include_blank: 'Entrada', class: 'input-times'}
        .columns.small-9.medium-5.large-4= select_tag 'fri[]', options_for_select(Institution.times, @item.settings.fri[1]), {include_blank: 'Salida', class: 'input-times'}
    .control
      .row.align-middle
        .columns.small-6.medium-5.large-4= f.label :mon, 'Sábado'
        .columns.small-9.medium-5.large-4= select_tag 'sat[]', options_for_select(Institution.times, @item.settings.sat[0]), {include_blank: 'Entrada', class: 'input-times'}
        .columns.small-9.medium-5.large-4= select_tag 'sat[]', options_for_select(Institution.times, @item.settings.sat[1]), {include_blank: 'Salida', class: 'input-times'}
    %br
    .control
      .row.align-middle
        .columns
          %strong
            Días hábiles para cerrar una gestión
    .control
      .row.align-middle
        .columns.small-6.medium-5.large-4= f.label :response_days, 'Días'
        .columns.small-9.medium-5.large-4= text_field_tag :response_days, @item.settings.response_days
    %br
    .control
      .row.align-middle
        .columns
          %strong
            Días de asueto (Por favor marque los días en el calendario)
          %br
          %br
          #datepicker
          = hidden_field_tag 'days', @item.settings.holidays, id: 'days'
    .control
      .row.align-center.align-justify
        .columns.small-5
        .columns.small-18
          = f.button type: :submit do
            %i.material-icons save
            Actualizar

app/views/panel/institutions/_table.haml
%script{ type: 'text/ng-template', id: '/clear-filters.html' }
  .clear-filters
    = link_to nil, 'ng-click' => 'clearFilters($event)' do
      %i.material-icons clear
      Remover filtros

%script{ type: 'text/ng-template', id: '/date-filter-from-template.html' }
  .date-range-picker-container
    %span{ 'ng-click' => 'showCalendarPicker($event)', 'ng-class' => "string2date(params.filter()[name]) ? 'has-content' : null" }
      {{ (string2date(params.filter()[name]) | date:'dd/MM/yyyy') || 'Desde' }}
    %mighty-datepicker.date-range-picker{ name: '{{name}}', 'ng-disabled' => '$filterRow.disabled', 'ng-model' => "params.filter()[name]", options: 'dateRangePickerOptions', 'range-from' => 'true', before: "params.filter()[name.replace('_gteq', '_lteq')]" }

%script{ type: 'text/ng-template', id: '/date-filter-to-template.html' }
  .date-range-picker-container
    %span{ 'ng-click' => 'showCalendarPicker($event)', 'ng-class' => "string2date(params.filter()[name]) ? 'has-content' : null" }
      {{ (string2date(params.filter()[name]) | date:'dd/MM/yyyy') || 'Hasta' }}
    %mighty-datepicker.date-range-picker{ name: '{{name}}', 'ng-disabled' => '$filterRow.disabled', 'ng-model' => "params.filter()[name]", options: 'dateRangePickerOptions', 'range-to' => 'true', after: "params.filter()[name.replace('_lteq', '_gteq')]" }

.table-container
  %table{ ng: { table: 'table.tableParams', table_columns_binding: 'table.cols' }}
    %tr{ ng: { repeat: 'item in $data' }}
      -# %td
      -#   %input{ type: :checkbox, class: 'decorated-checkbox box', 'checklist-model' => 'checkboxes.ids', 'checklist-value' => 'item.id' }
      %td{ data: { title: '', filter: "{ actions: '/clear-filters.html' }" }}
        .action-buttons
          - if can? :unlock, Institution
            = link_to "#{model.to_s.pluralize.underscore}/{{ item.id }}/unlock", class: 'text', title: 'Desbloquear institución', data: { confirm: '¿Desea permitir que {{item.name}} haga ajustes en los casos ya cerrados?' }, 'ng-hide' => "{{ item.can_edit }}" do
              %i.material-icons lock
            = link_to nil, class: 'text-success', title: 'Institución desbloqueada por 1 hora', 'ng-show' => '{{item.can_edit}}' do
              %i.material-icons lock_open
          - if can? :edit, Institution
            = link_to "#{model.to_s.pluralize.underscore}/{{ item.id }}/edit", class: 'text-primary', title: 'Editar institución' do
              %i.material-icons border_color
          - if can? :destroy, Institution
            = link_to "#{model.to_s.pluralize.underscore}/{{ item.id }}", class: 'text-danger', method: :delete, data: { confirm: '¿Está seguro?' }, title: 'Eliminar institución' do
              %i.material-icons delete
      %td{ data: { title: "'Acrónimo'" }, 'ng-if' => 'true', filter: "{ acronym_icont: 'text' }", sortable: "'acronym'" } {{ item.acronym }}
      %td{ data: { title: "'Nombre'" }, 'ng-if' => 'true', filter: "{ name_icont: 'text' }", sortable: "'name'" } {{ item.name }}
      - if current_user.has_role?(:admin)
        %td{ data: { title: "'Fecha de creación'" }, 'ng-if' => 'true', filter: "table.dateFilter('created_at')", sortable: "'created_at'" } {{ item.created_at | date:'dd/MM/yy hh:mm a' }}
        %td{ data: { title: "'Fecha de actualización'" }, 'ng-if' => 'true', filter: "table.dateFilter('updated_at')", sortable: "'updated_at'" } {{ item.updated_at | date:'dd/MM/yyyy hh:mm a' }}

app/views/panel/institutions/form.haml
.header
  .row.align-middle
    .columns
      %h1
        %i.material-icons input
        = t model.to_s.underscore, scope: 'activerecord.models', count: 1
    .columns.shrink

.breacrumb
  = render_breadcrumbs separator: ' / '

.wrapper
  .row.align-center
    .columns.large-16
      .container
        - if @item.errors.any?
          .alert.error
            No se pudo guardar el registro, por favor, revise los campos del formulario

        - if flash[:saved]
          .alert.success
            Registro guardado correctamente
        .tabs
          = link_to nil, class: 'active', data: { tab: '#general' } do
            Información general

          = link_to nil, data: { tab: '#schedules' } do
            Horarios y asuetos

        #general
          = form_for [:panel, @item], as: :item do |f|
            .form

              = render partial: 'form', locals: { f: f }

              .control
                .row.align-center.align-justify
                  .columns.small-5
                  .columns.small-18
                    = f.button type: :submit do
                      %i.material-icons save
                      Guardar
        #schedules
          .form
            = render partial: 'settings'