config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :expedients, only: [:create] do
    get :check, on: :collection
    get :verify, on: :collection
    get :thanks, on: :member
  end

  resources :pages, only: [] do
    get :find, on: :collection
    get :thanks, on: :collection
  end

  get 'fati', to: 'home#new_whatsapp', as: :new_whatsapp
  post 'register_whatsapp', to: 'home#register_whatsapp', as: :register_whatsapp

  namespace :panel do
    root to: 'home#index'

    resources :profile, only: [:edit, :update]
    resources :versions, only: [:show]

    resources :admin_settings, only: [] do
      put :table_columns, on: :collection
    end

    resources :institution_calendars, only: [:index, :show, :new] do
      resources :calendar_events, only: [:new, :edit]
    end

    resources :expedients do
      put :updates, on: :collection
      put :destroys, on: :collection
      get :list, on: :collection
      get :documents, on: :member
      post :redirect, on: :member
      post :tags, on: :member
      resources :events, only: [:create, :update]
      resources :managements, only: [:create]
    end

    resources :managements, only: [:update] do
      post :close, on: :member
      resources :comments, only: [:create]
    end

    resources :statistics, only: [:index] do
      get :managementsassigned, on: :member
      get :administrativearea, on: :member
      get :scategories,        on: :member
      get :entryways,          on: :member
      get :branches,           on: :member
      get :details,            on: :collection
      get :cities,             on: :member
      get :tags,               on: :member
    end

    [
      :institutions,
      :oir_addresses,
      :calendar_events,
      :information_requests,
      :users,
      :occupations,
      :documents,
      :entry_ways,
      :management_categories,
      :branches
    ].each do |resource|
      resources resource do
        put :updates, on: :collection
        put :destroys, on: :collection
        get :list, on: :collection
      end
    end

    resources :institutions, only: [] do
      member do
        post 'settings'
        get 'unlock'
      end
    end
    resources :branches, only: [] do
      member do
        post 'settings'
        get 'unlock'
      end
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true
#
class HomeController < ApplicationController
  http_basic_authenticate_with name: ENV['WHATSAPP_NAME'], password: ENV['WHATSAPP_PASS'], except: :index

  def index
    @expedient = Expedient.new
    @institutions = Institution.visible.includes(:branches)
    @states = State.includes(:cities)
  end

  def new_whatsapp
    @today = Whatsapp.where(created_at: Time.current.beginning_of_day .. Time.current.end_of_day).order(:created_at)
    @whatsapp = Whatsapp.new
  end

  def register_whatsapp
    @whatsapp = Whatsapp.new params_whatsapp
    if @whatsapp.save
      redirect_to new_whatsapp_url and return
    else
      @today = Whatsapp.where(created_at: Time.current.beginning_of_day .. Time.current.end_of_day).order(:created_at)
      render :new_whatsapp
    end
  end

  private
    def params_whatsapp
      params.require(:whatsapp).permit(:phone, :message, :kind)
    end
end

app/controllers/panel/home_controller.rb
# frozen_string_literal: true
module Panel
  #
  class HomeController < PanelController
    skip_load_resource
    skip_authorize_resource
    def index
      # Last day expedients
      last_day = Date.current - 1.day
      @last_day_expedients = Expedient
        .accessible_by(current_ability, :read)
        .where(received_at: last_day.beginning_of_day .. last_day.end_of_day)
        .reorder(received_at: :desc)
        .limit(10)
      # Current year expedients by branches
      if current_user.one_institution?
        @current_year_expedients = Expedient
          .accessible_by(current_ability, :read)
          .select(:id, :branch_id)
          .where(received_at: Time.current.beginning_of_year .. Time.current.end_of_year)
          .includes(:branch)
          .group_by{|e| e.branch.try(:name)}
          .sort_by{|k, v| k.to_s}.to_h
      end
      # Managements by kind and category name
      mids = Management.accessible_by(current_ability, :read).pluck(:id)
      @management_categories = Management
        .where(id: mids)
        .select("managements.kind AS kind, management_categories.name AS name, count(managements.kind) AS total")
        .joins(:management_category)
        .group('managements.kind, management_categories.name')
        .order('managements.kind asc, management_categories.name asc, count(managements.kind) desc')
      # Expedients expired without communication
      three_business_days_ago = 3.business_days.before(Date.current)
      @expired_expedients = Expedient
        .accessible_by(current_ability, :read)
        .where(state: 'new')
        .where('received_at < ?', three_business_days_ago)
        .order(received_at: :desc)
        .limit(5)
      # Open managements expired
      @expired_managements = Management
        .where(id: mids)
        .where(state: 'process')
        .where(deadline_at: Date.current .. 3.business_days.from_now)
        .order(deadline_at: :asc)
        .limit(5)
      # Expedients total by institution / branch
      # unless current_user.one_institution?
      #   # TODO change later with a counter_cache column
      #   @by_institutions = Institution.accessible_by(current_ability, :read)
      #     .includes(:expedients, branches: :expedients)
      # end
    end
  end
end

app/views/home/index.haml
.form
  .row.expanded.align-justify
    .columns.small-offset-1.small-22.small-offset-1.large-13.large-offset-1.medium-12.medium-offset-1
      .step-form
        = form_for @expedient, url: expedients_url, html: { class: 'dropzone', data: {preview: ".dropzone-previews-expedient"} } do |f|
          - if @expedient.errors.any?
            .alert.error
              - @expedient.errors.each do |k, m|
                = m
          %section
            .row
              .columns.small-24
                %h2.question
                  * Cuentános tu caso
                %label
                  Describe de manera clara y sencilla la situación o inconveniente que viviste en la institución del gobierno
                = f.text_area :comment, rows: 2
              .columns.small-24
                %h2.question
                  * ¿En cuál institución sucedió tu caso?
                = f.collection_select :institution_id, @institutions, :id, :name, {prompt: 'Seleccione'},  { data: {dependent: '', target: 'expedient-branch-id', child: 'expedient-branch-id', hidden: true} }
              .columns.small-24
                %label
                  ¿En cuál dependencia?
                = f.grouped_collection_select :branch_id, @institutions, :branches, :name, :id, :name, {prompt: 'Seleccione'}, {class: 'expedient-branch-id'}
              .columns.small-24
                .dz-default.dz-message
                  .dropzone-previews-expedient
                  %span
                    %span.curved
                      Seleccione o arrastre acá sus documentos
                  %br
                  %br
                  .text-center
                    %span
                      Puedes subir JPG, PNG, PDF, DOCX
                %small
                  * Obligatorios
                .text-center
                  = link_to 'Continuar', 'javascript:void(0)', class: 'orange-button next-section disabled'
                %br
          %section.hide
            .row
              .columns.small-24
                %h2.question
                  Para que el caso sea atendido ágilmente, agregue los siguientes datos, si aplica o los posee:
                %br
                %label
                  Fecha y hora en la que sucedió
                = f.datetime_select :happened_at, {prompt: { day: 'Día', month: 'Mes', year: 'Año', hour: 'Hora', minute: 'Minutos' }, default: nil, end_year: Date.current.year, start_year: (Date.current - 10.years).year}, {class: 'wauto'}
                %label
                  Lugar donde sucedió
                = f.text_field :place
                %label
                  Placa del vehículo nacional
                = f.text_field :national_license_plate
                %label
                  Nombre del personal involucrado
                = f.text_field :personnel_name
                %label
                  Nombre del proceso
                = f.text_field :process_name
            .row
              .columns
                %br
                .text-center
                  = link_to 'Regresar', 'javascript:void(0)', class: 'orange-button prev-section'
                  = link_to 'Continuar', 'javascript:void(0)', class: 'orange-button next-section'
                %br
          %section.hide
            .row
              .columns.small-24.medium-17.second-step
                %label.black
                  * Nombre
                  %small
                    Escribe tu nombre para contactarte
                = f.text_field :contact, required: true
              .columns.small-24.medium-6.medium-offset-1
                %label.black
                  * Teléfono
                = f.text_field :phone, required: true
              .columns.small-24.second-step
                %label.black
                  Correo electrónico
                = f.email_field :email
              .columns.small-24.medium-4.second-step
                %label.black
                  Edad
                = f.number_field :age
              .columns.small-24.medium-5.medium-offset-1
                %label.black
                  Sexo
                = f.select :gender, options_for_select([['Hombre', 'm'], ['Mujer', 'f']]), prompt: true
              .columns.small-24.medium-6.medium-offset-1
                %label.black
                  Departamento
                = f.collection_select :state_id, @states, :id, :name, {prompt: 'Seleccione'}, {data: {dependent: '', target: 'select-city'}}
              .columns.small-24.medium-6.medium-offset-1
                %label.black
                  Municipio
                = f.grouped_collection_select :city_id, @states, :cities, :name, :id, :name, {prompt: 'Seleccione'}, {class: 'select-city'}
            .row
              .columns
                %small
                  * Obligatorios
                - if Rails.env.production?
                  %center
                    = recaptcha_tags
                %br
                .text-center
                  = link_to 'Regresar', 'javascript:void(0)', class: 'orange-button prev-section'
                  %button{ type: 'submit', class: 'dark-orange-button' }
                    Finalizar
                %br
    = render 'layouts/application/info_lateral'

app/views/home/new_whatsapp.haml
.row.expanded.align-justify
  .columns.small-offset-1.small-22.small-offset-1.large-13.large-offset-1.medium-12.medium-offset-1
    %br
    = form_for @whatsapp, url: register_whatsapp_url, html: {class: 'form'} do |f|
      %label
        Teléfono
        = f.text_field :phone
      %label
        Mensaje
        = f.text_area :message
      %label
        Tipo de caso
      .radios
        = f.radio_button :kind, 'conectate'
        = f.label :kind_conectate, 'Conéctate'
        = f.radio_button :kind, 'consulta'
        = f.label :kind_consulta, 'Consulta'
        = f.radio_button :kind, 'denuncia'
        = f.label :kind_denuncia, 'Denuncia'
        = f.radio_button :kind, 'corrupcion'
        = f.label :kind_corrupcion, 'Corrupción'
      %br
      = f.submit 'Guardar'
  .columns.small-24.large-7.medium-10.info
    .row.align-middle
      .columns.small-offset-2.small-22
        %br
        Casos registrados este día:
        %br
        - if @today.any?
          %ol
            - @today.each do |w|
              %li
                %strong= w.created_at.try(:strftime, '%H:%M')
                = w.phone
        - else
          %strong
            No se ha registrado ningún caso este día