config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :expedients, only: [:create] do
    get :check, on: :collection
    get :verify, on: :collection
    get :thanks, on: :member
  end

  resources :pages, only: [] do
    get :find, on: :collection
    get :thanks, on: :collection
  end

  get 'fati', to: 'home#new_whatsapp', as: :new_whatsapp
  post 'register_whatsapp', to: 'home#register_whatsapp', as: :register_whatsapp

  namespace :panel do
    root to: 'home#index'

    resources :profile, only: [:edit, :update]
    resources :versions, only: [:show]

    resources :admin_settings, only: [] do
      put :table_columns, on: :collection
    end

    resources :institution_calendars, only: [:index, :show, :new] do
      resources :calendar_events, only: [:new, :edit]
    end

    resources :expedients do
      put :updates, on: :collection
      put :destroys, on: :collection
      get :list, on: :collection
      get :documents, on: :member
      post :redirect, on: :member
      post :tags, on: :member
      resources :events, only: [:create, :update]
      resources :managements, only: [:create]
    end

    resources :managements, only: [:update] do
      post :close, on: :member
      resources :comments, only: [:create]
    end

    resources :statistics, only: [:index] do
      get :managementsassigned, on: :member
      get :administrativearea, on: :member
      get :scategories,        on: :member
      get :entryways,          on: :member
      get :branches,           on: :member
      get :details,            on: :collection
      get :cities,             on: :member
      get :tags,               on: :member
    end

    [
      :institutions,
      :oir_addresses,
      :calendar_events,
      :information_requests,
      :users,
      :occupations,
      :documents,
      :entry_ways,
      :management_categories,
      :branches
    ].each do |resource|
      resources resource do
        put :updates, on: :collection
        put :destroys, on: :collection
        get :list, on: :collection
      end
    end

    resources :institutions, only: [] do
      member do
        post 'settings'
        get 'unlock'
      end
    end
    resources :branches, only: [] do
      member do
        post 'settings'
        get 'unlock'
      end
    end
  end
end

app/models/institution.rb
class Institution < ApplicationRecord
  include RailsSettings::Extend

  has_and_belongs_to_many :users
  has_many :branches, dependent: :destroy
  has_many :expedients, dependent: :destroy

  default_scope { order(acts_as_label) }
  scope :visible,            -> { where(visible: true) }

  has_attached_file :avatar, styles: { profile: '150x150>' }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  after_create :prepare_extra_data

  ransacker :name, type: :string do
    Arel.sql("UNACCENT(\"#{table_name}\".\"name\")")
  end

  def self.acts_as_label
    :name
  end

  def acts_as_label
    send(self.class.acts_as_label)
  end

  def statistic_by_type?
    self.statistic_by_type == {} ? true : false
  end

  def statistic_by_type
    r = self.expedients.group(:state).count.each_with_object({}) do |v, hash|
      hash[Expedient::STATE[v[0]].to_s] = v[1]
    end
    r
  end

  def statistic_by_kind?
    r=0
    k = self.statistic_by_kind
    k.each{|s| s[1] == 0 ? r += 1 : nil}
    r == k.length ? true : false
  end

  def statistic_by_kind
    Management.pluck(:kind).uniq.each_with_object({}) do |v, hash|
      hash[Management::KIND[v].to_s] = Management.where(expedient_id: self.expedients.ids, kind: v).count
    end
  end

  def statistic_contact_time?
    r=0
    t = self.statistic_contact_time
    t.each{|s| s[1] == 0 ? r += 1 : nil}
    r == t.length ? true : false
  end

  def statistic_contact_time
    e = self.expedients
    less_48hours     = e.where("contact_business_days <= 2").count
    more_48hours     = e.where("contact_business_days > 2").count
    wo_contact       = e.where(anonymous: true).count
    failed_contact   = e.joins(:events).where("expedients.contact_business_days IS NULL").where("events.state = 'failed_communication_attempt'").distinct.count

    [
      ["Menos de 48 horas", less_48hours],
      ["Más de 48 horas", more_48hours],
      ["Contacto fallido", failed_contact],
      ["Sin contacto", wo_contact]
    ]
  end

  def self.times
    h = []
    start_time = Time.now.beginning_of_day + 6.hours
    end_time = start_time + 12.hours
    while start_time <= end_time
      h << start_time.strftime('%H:%M')
      start_time += 30.minutes
    end
    return h
  end

  # Business time config
  def set_business_config
    s = settings.get_all
    BusinessTime::Config.work_hours = work_hours(s)
    BusinessTime::Config.work_week = work_hours(s).keys
    holidays(s).each{|h| BusinessTime::Config.holidays << h }
  end

  def schedule_can_edit_closure
    self.update_column(:can_edit, false)
  end
  handle_asynchronously :schedule_can_edit_closure, :run_at => Proc.new { ENV['ADJUSTMENT_MINUTES_TIME'].to_i.minutes.from_now }


  private
    def prepare_extra_data
      # create the entry ways
      begin
        Config['entry_ways']['institution'].each do |k, v|
          EntryWay.where(institution_id: self.id, name: k, classification: v).first_or_create
        end
      rescue
      end
      # create the management categories
      begin
        Config['management_categories'].each do |k, values|
          values.each do |v|
            ManagementCategory.where(institution_id: self.id, kind: k, name: v).first_or_create
          end
        end
      rescue
      end
    end

    def work_hours(s)
      {
        :mon => s[:mon],
        :tue => s[:tue],
        :wed => s[:wed],
        :thu => s[:thu],
        :fri => s[:fri],
        :sat => s[:sat]
      }.reject { |k,v| v.all?(&:blank?) }
    end

    def holidays(s)
      s[:holidays].split(',').map{|d| Date.parse(d) rescue nil}.compact
    end

end

app/controllers/concerns/panel/crud.rb
# frozen_string_literal: true
module Panel
  #
  module Crud
    extend ActiveSupport::Concern

    included do
      respond_to :html
      before_action :set_item, only: [:show, :edit, :update, :destroy]
      before_action :set_uniq_institution!, only: [:update]

      helper_method :model
    end

    def index
      respond_to do |format|
        format.json { super }
        format.csv  { super }
        format.html { respond_to_html }
      end
    end

    def respond_to_html
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(:many), index_url
      render template: 'concerns/panel/index'
    end

    def new
      @item = model.new

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def create
      @item = model.new item_params
      set_uniq_institution!
      return redirect_to(edit_url, flash: { saved: true }) if @item.save

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def edit
      init_form
      breadcrumbs_for(:edit)

      render template: 'concerns/panel/form'
    end

    def update
      respond_to do |format|
        format.json { super }
        format.html do
          return redirect_to(edit_url, flash: { saved: true }) if
            @item.update_attributes(item_params)

          breadcrumbs_for(:edit)
          init_form
          render template: 'concerns/panel/form'
        end
      end
    end

    def destroy
      if @item.destroy
        redirect_to index_url, flash: { destroyed: true }
      else
        redirect_to index_url, flash: { destroyed: false, errors: @item.errors.full_messages }
      end
    end

    def init_form
    end

    def set_uniq_institution!
      return unless @item.respond_to? :institution_id
      #return unless current_user.one_institution?
      @item.institution_id = current_user.uniq_institution.try(:id)
    end

    private

    def item_params
      perms = params.require(:item).permit(permits)
      #perms.delete(:institution_id) if current_user.one_institution?
      perms
    end

    def set_item
      @item = if model.respond_to?(:friendly)
                model.friendly.find params[:id]
              else
                model.find params[:id]
              end
    end

    def show_url
      url_for(action: :show, id: @item)
    end

    def edit_url
      url_for(action: :edit, id: @item)
    end

    def index_url
      url_for(controller: model.to_s.underscore.pluralize, action: :index)
    end

    def humanized_model_name(count = 1)
      t(model.to_s.underscore, scope: 'activerecord.models', count: count)
    end

    def breadcrumbs_for(action)
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(count: :many), index_url
      add_breadcrumb t(action.to_s), nil
    end
  end
end

app/controllers/concerns/panel/multiple.rb
# frozen_string_literal: true
module Panel
  #
  module Multiple
    extend ActiveSupport::Concern

    included do
      respond_to :json

      before_action :ngtable_to_rails_filter_param, only: [:index]
      before_action :ngtable_to_rails_sort_param,   only: [:index]
    end

    def update
      respond_to do |format|
        format.html { super }
        format.json do
          sleep 0.5

          return render json: { success: true } if
            @item.update_attributes(item_params)

          render json: { success: false }
        end
      end
    end

    def updates
      model.where(id: params[:ids]).each do |item|
        item.assign_attributes(item_params.to_hash)
        item.save(validate: false)
      end
    end

    def destroys
      model.where(id: params[:ids]).each(&:destroy)
    end

    def index
      respond_to do |format|
        format.html { super }
        format.csv  { super }
        format.json { respond_to_json }
      end
    end

    def respond_to_json
      @q = model.ransack(params[:filter])
      @c = @q.result.paginate(page: params[:page], per_page: params[:count])

      render json: json_result(@c)
    end

    def json_result(collection)
      {
        result:        json_parsed(collection),
        total_entries: collection.total_entries,
        admin_setting: current_user.admin_setting
      }
    end

    def json_parsed(c)
      c.decorate.as_json(include: json_includes, methods: json_methods)
    end

    def json_includes
      nil
    end

    def json_methods
      nil
    end

    def list
      render json: model
        .select(:id, model.acts_as_label)
        .order(model.acts_as_label)
        .to_json
    end

    private

    def ngtable_to_rails_filter_param
      return unless params.key?(:filter)
      params[:filter]
        .update(params[:filter]) { |_k, v| URI.decode(v) }
        .delete_if { |_k, v| v == 'null' }
    end

    def ngtable_to_rails_sort_param
      return unless params.key?(:sorting)

      params[:filter] ||= {}
      params[:filter][:s] = params[:sorting].flatten.join(' ')
    end
  end
end

app/controllers/panel/admin_settings_controller.rb
# frozen_string_literal: true
module Panel
  #
  class AdminSettingsController < PanelController
    before_action :fetch_admin_setting

    def table_columns
      @admin_setting.update_table_columns(item_params[:table_columns])
    end

    # private

    def item_params
      params.require(:admin_setting).tap do |whitelisted|
        whitelisted[:table_columns] = params[:admin_setting][:table_columns]
      end
    end

    def fetch_admin_setting
      @admin_setting = AdminSetting
                       .where(user_id: current_user.id)
                       .first_or_create
    end
  end
end

app/controllers/panel/branches_controller.rb
# frozen_string_literal: true
module Panel
  #
  class BranchesController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      Branch
    end

    def permits
      [:name, :address, :institution_id]
    end

    def respond_to_json
      @q = model.accessible_by(current_ability)
      @q = @q.ransack(params[:filter])
      @c = @q.result.paginate(page: params[:page], per_page: params[:count])

      render json: json_result(@c)
    end

    def edit
      init_form
      breadcrumbs_for(:edit)

      render template: 'panel/branches/form'
    end

    def new
      @item = model.new

      init_form
      breadcrumbs_for(:new)
      render template: 'panel/branches/form'
    end

    def create
      @item = model.new item_params
      set_uniq_institution! if current_user.one_institution?
      if @item.save
        return redirect_to(edit_url, flash: { saved: true })
      end
      init_form
      breadcrumbs_for(:new)
      render template: 'panel/branches/form'
    end

    def update
      @item.attributes = item_params
      if @item.save
        return redirect_to(edit_url, flash: { saved: true })
      end
      init_form
      breadcrumbs_for(:edit)
      render template: 'panel/branches/form'
    end

    def init_form
      if current_user.has_role?("admin")
        @institutions = Institution.order(Institution.acts_as_label)
      else
        @institutions = Institution.where("id IN (?)", current_user.institution_ids)
      end
    end

    def settings
      branch = Branch.find params[:id]
      redirect_to panel_branches_url and return unless branch

      branch.settings.mon = params[:mon]
      branch.settings.tue = params[:tue]
      branch.settings.wed = params[:wed]
      branch.settings.thu = params[:thu]
      branch.settings.fri = params[:fri]
      branch.settings.sat = params[:sat]
      branch.settings.holidays = params[:days]
      branch.settings.response_days = params[:response_days]
      redirect_to edit_panel_branch_url, flash: {saved: true}
    end

    def unlock
      branch = Branch.find params[:id]
      redirect_to panel_branches_url and return if branch.can_edit?
      branch.update_column(:can_edit, true)
      branch.schedule_can_edit_closure
      redirect_to panel_branches_url and return
    end

    private
    def json_methods
      [ :institution_name ]
    end

  end
end

app/controllers/panel/calendar_events_controller.rb
# frozen_string_literal: true
module Panel
  #
  class CalendarEventsController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      CalendarEvent
    end

    def create
      @item = model.new item_params
      @item.user_id = current_user.id
      @item.institution_calendar_id = params[:institution_calendar_id]
      return redirect_to(edit_url, flash: { saved: true }) if @item.save

      init_form
      breadcrumbs_for(:new)
      render template: 'concerns/panel/form'
    end

    def permits
      [:name, :description, :kind, :start_at, :end_at, :repetitive]
    end

    def exportable_fields
      [:name]
    end

    def respond_to_html
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb humanized_model_name(:many), index_url
      render template: 'panel/calendar_events/index'
    end

    def breadcrumbs_for(action)
      add_breadcrumb t('home'), panel_root_url
      add_breadcrumb "Listado de eventos", panel_institution_calendar_url(params[:institution_calendar_id])
      add_breadcrumb t(action.to_s), nil
    end

  end
end

app/controllers/panel/comments_controller.rb
# frozen_string_literal: true
module Panel
  #
  class CommentsController < PanelController
    include Panel::Crud
    include Panel::Multiple

    def model
      Comment
    end

    def permits
      [:comment]
    end

    def exportable_fields
      []
    end

    def create
      management = Management.find params[:management_id]
      item = management.expedient
      comment = management.comments.new item_params
      comment.user_id = current_user.id
      success = comment.save
      respond_to do |format|
        # Save assets
        if params[:file]
          params[:file].each do |k, file|
            Asset.create attachment: file, assetable: comment
          end
        end
        format.html {
          return redirect_to panel_expedient_url(item, anchor: "management-#{management.id}")
        }
        format.json {
          render json: {code: 200, item: comment, redirect_url: panel_expedient_url(item, anchor: "management-#{management.id}")}
        }
      end
    end

    def item_params
      perms = params.require(:comment).permit(permits)
      perms
    end


  end
end

app/controllers/panel/occupations_controller.rb
# frozen_string_literal: true
module Panel
  #
  class OccupationsController < PanelController
    include Panel::Crud
    include Panel::Multiple
    
    def model
      Occupation
    end

    def permits
      [:name]
    end

    def exportable_fields
      [:name]
    end

  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/views/panel/users/_actions.haml
.row.align-middle
  .columns.small-6
    .actions
      .row.align-stretch
        .columns.shrink
          %input.decorated-checkbox.box{ type: :checkbox, class: 'all', ng: { model: 'checkboxes.checked' }}

        .columns
          %div{ ng: { show: 'checkboxes.checked || indeterminate' }}
            = link_to nil, class: 'btn', 'ng-click' => 'deleteSelection($event)' do
              %i.material-icons delete

          %strong.total-entries{ 'ng-bind' => "total_entries + ' Registros'" }


  .columns.small-18
    .visibility-controls
      = label_tag nil, 'ng-repeat' => 'col in table.cols' do
        %input{ type: :checkbox, ng: { model_options: "{ getterSetter: true }", model: 'col.show' }}
        %span {{ col.title() }}

app/views/panel/users/_form.haml
.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :name
    .columns.small-18= f.text_field :name

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :email
    .columns.small-18= f.text_field :email

.control
  .row.align-middle.align-justify
    .columns.small-5= label_tag "role", "Rol"
    .columns.small-18= select_tag "role", options_for_select(@allowed_roles.map{ |i| [t(i, scope: 'activerecord.enum.user.role'), i] }, @roles.try(:name)), prompt: "Permisos disponibles", required: true

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :administrative_area
    .columns.small-18
      = f.text_field :administrative_area
      %small
        * Requerido si es un usuario de unidad administrativa


.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :password
    .columns.small-18= f.password_field :password

.control
  .row.align-middle.align-justify
    .columns.small-5= f.label :password_confirmation
    .columns.small-18= f.password_field :password_confirmation

- if current_user.has_role?(:admin)
  %br
  %br
  %h2
    Instituciones que puede administrar
  = hidden_field_tag 'item[institution_ids][]', nil
  - @institutions.each do |institution|

    .control
      .row.align-middle.align-justify
        .columns= f.label :institution_ids, institution.name, for: "institution_ids_#{institution.id}"
        .columns.shrink= check_box_tag 'item[institution_ids][]', institution.id, f.object.institutions.include?(institution), class: 'decorated-checkbox box', id: "institution_ids_#{institution.id}"

- if @branches.any?
  %br
  %br
  %h2
    Dependencias que puede administrar
    %small
      *Aplica para rol Administrador Junior
  = hidden_field_tag 'item[branch_ids][]', nil
  - @branches.each do |branch|
    .control
      .row.align-middle.align-justify
        .columns= f.label :branch_ids, branch.name, for: "branch_ids_#{branch.id}"
        .columns.shrink= check_box_tag 'item[branch_ids][]', branch.id, f.object.branches.include?(branch), class: 'decorated-checkbox box', id: "branch_ids_#{branch.id}"

app/views/panel/users/_table.haml
%script{ type: 'text/ng-template', id: '/clear-filters.html' }
  .clear-filters
    = link_to nil, 'ng-click' => 'clearFilters($event)' do
      %i.material-icons clear
      Remover filtros

.table-container
  %table{ ng: { table: 'table.tableParams', table_columns_binding: 'table.cols' }}
    %tr{ ng: { repeat: 'item in $data' }}
      %td
        %input{ type: :checkbox, class: 'decorated-checkbox box', 'checklist-model' => 'checkboxes.ids', 'checklist-value' => 'item.id' }
      %td{ data: { title: '', filter: "{ actions: '/clear-filters.html' }" }}
        .action-buttons
          = link_to "#{model.to_s.pluralize.underscore}/{{ item.id }}/edit", class: 'text-primary' do
            %i.material-icons border_color
            Editar

          = link_to "#{model.to_s.pluralize.underscore}/{{ item.id }}", class: 'text-danger', method: :delete, data: { confirm: '¿Está seguro?' } do
            %i.material-icons delete
            Eliminar

      %td{ data: { title: "'Roles'" }, 'ng-if' => 'true', filter: "{ roles_name_icont: 'text' }", sortable: "'roles_name_s'" } {{ item.roles_name_s }}
      - unless current_user.one_institution?
        %td{ data: { title: "'Instituciones'" }, 'ng-if' => 'true', filter: "{ institutions_name_icont: 'text' }", sortable: "'institutions_name'" } {{ item.institutions_name }}
      %td{ data: { title: "'Dependencia'" }, 'ng-if' => 'true', filter: "{ branches_name_icont: 'text' }", sortable: "'branches_name'" } {{ item.branches_name }}
      %td{ data: { title: "'Unidad administrativa'" }, 'ng-if' => 'true', filter: "{ administrative_area_icont: 'text' }", sortable: "'administrative_area'" } {{ item.administrative_area }}
      %td{ data: { title: "'Nombre'" }, 'ng-if' => 'true', filter: "{ name_icont: 'text' }", sortable: "'name'" } {{ item.name }}
      %td{ data: { title: "'Email'" }, 'ng-if' => 'true', filter: "{ email_icont: 'text' }", sortable: "'email'" } {{ item.email }}